name: Build workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lk-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Install pyhton2
      run: sudo apt-get install python2
    - name: Cache GCC for Android
      id: cache-gcc
      uses: actions/cache@v4
      with:
        path: ~/gcc-toolchain
        key: gcc-toolchain
    - name: Download GCC for Android
      if: steps.cache-gcc.outputs.cache-hit != 'true'
      run: |
        git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 ~/gcc-toolchain
        cd ~/gcc-toolchain
        git checkout e9b2ab0932573a0ca90cad11ab75d9619f19c458
    - name: Build the bootloader
      run: |
        export python=python2
        touch ./main_dtb_header.bin # no dtb is required for  k39tv1_bsp_1g
        TOOLCHAIN_PREFIX=~/gcc-toolchain/bin/arm-linux-androideabi- make  k39tv1_bsp_1g
    - name : Upload bootloader
      uses: actions/upload-artifact@v4
      with:
        name:  k39tv1_bsp_1g_lk-signed
        path: /home/runner/work/lk/lk/build- k39tv1_bsp_1g/lk-sign.img
